services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intrusion-api
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: intrusion-ui
    ports:
      - "8501:8501"
    depends_on:
      - fastapi